# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: desmafagafigando
    ports:
      - "8567:3306"

  frontend:
    container_name: frontend
    build: ..\frontend
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
