# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  desmafagafigandoapi:
    image: desmafagafigandoapi
    build:
      context: .
      dockerfile: backend/desmafagafigando.api/Dockerfile
    ports:
      - 5001:5001
